"""empty message

Revision ID: 4c9a8014ba74
Revises: 94acf5bb06fc
Create Date: 2018-07-29 13:03:07.881143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9a8014ba74'
down_revision = '94acf5bb06fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test2', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
