"""empty message

Revision ID: 92d4b6f2c81e
Revises: 252019e2e9c7
Create Date: 2018-08-01 10:56:47.012509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d4b6f2c81e'
down_revision = '252019e2e9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name3', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone3', sa.String(), nullable=True))
    op.add_column('users', sa.Column('relation1', sa.String(), nullable=True))
    op.add_column('users', sa.Column('relation2', sa.String(), nullable=True))
    op.add_column('users', sa.Column('relation3', sa.String(), nullable=True))
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'relation3')
    op.drop_column('users', 'relation2')
    op.drop_column('users', 'relation1')
    op.drop_column('users', 'phone3')
    op.drop_column('users', 'name3')
    # ### end Alembic commands ###
