"""empty message

Revision ID: 94acf5bb06fc
Revises: 
Create Date: 2018-07-29 11:13:23.082719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94acf5bb06fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('test', sa.String(), nullable=True),
    sa.Column('test2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
