"""empty message

Revision ID: 957abc1f270d
Revises: 
Create Date: 2018-07-26 12:50:54.743579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957abc1f270d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('yourmodel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yourmodel')
    op.drop_table('users')
    # ### end Alembic commands ###
